### ISSUE TITLE
Repositoryに@Paramが必要のようです。

### ISSUE THREAD

**Issue by akiraabe** [MasatoshiTada/oauth2-with-spring-security-51#1]
Qiitaの記事やjsugのスライドを参考にさせていただきました。ありがとうございます。
to-doのupdate(完了済みにする)に関して、Repositoryのパラメータに@Paramを明示的に付けないと私の環境では稼働しませんでした。（keycloak-6.0.0を使っています。あとは同じはずです）

ご確認頂ければ幸いです。

@Query("UPDATE todo SET done = true WHERE id = :id")
@Modifying
public void updateDoneById(**@Param("id")** Integer id);

**Comment by MasatoshiTada** [comment]
@akiraabe コンパイルオプションに `-parameters` を付ければ、 `@Param` 無しでも実行できるはずです！ご確認お願いします。

**Comment by akiraabe** [comment]
ちょっと完全に試せてないですが、確かにメッセージに

Use @Param for query method parameters, or when on Java 8+ use the javac flag -parameters.

と出ているので、コンパイルオプション指定で行けそうですね。
ありがとうございました。結果は後日お知らせします。
